from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    buy_now,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    RegisterView,
    LoginView,
    LogoutView,
    ProfileView,
    SearchView,
    about_us,
    shipping_policy,
    terms_of_service,
    privacy_policy,
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('buy-now/<slug>/', buy_now, name='buy-now'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    # New authentication URLs
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    # Search URL
    path('search/', SearchView.as_view(), name='search'),
    path('about-us/', about_us, name='about-us'),
    path('shipping-policy/', shipping_policy, name='shipping-policy'),
    path('terms-of-service/', terms_of_service, name='terms-of-service'),
    path('privacy-policy/', privacy_policy, name='privacy-policy'),
]
